name: very_good_infinite_list
description: >-
  A Very Good Infinite List Widget created by Very Good Ventures.
  Comes in handy when making activity feeds, news feeds, or any feature that involves lazily fetching and rendering content for users to consume.
version: 0.1.0
repository: https://github.com/VeryGoodOpenSource/very_good_infinite_list
issue_tracker: https://github.com/VeryGoodOpenSource/very_good_infinite_list/issues
homepage: https://github.com/VeryGoodOpenSource/very_good_infinite_list
documentation: https://github.com/VeryGoodOpenSource/very_good_infinite_list

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4
